name: CI

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  cancel-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  static-check:
    runs-on: ubuntu-latest
    needs: cancel-workflow
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Clean build
        run: ./gradlew clean
      - name: Run ktlintDebug
        run: ./gradlew ktlintMainSourceSetCheck
      - name: Upload ktlint report
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ktlint-result
          path: ./**/build/reports/ktlint/**/*.html

  build:
    runs-on: ubuntu-latest
    needs: static-check
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Clean build
        run: ./gradlew clean
      - name: Setup Secrets
        run:  |
          cat << EOF > ./app/src/main/res/values/secrets.xml
          ${{ secrets.secrets_xml }}
          EOF
      - name: Setup google-services.json
        run:  |
          cat << EOF > ./app/google-services.json
          ${{ secrets.google_services_json }}
          EOF
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Run test
        run: ./gradlew test --stacktrace
      - name: Upload test report
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-result
          path: ./**/build/reports/tests/**
